server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/test?serverTimezone=Asia/Seoul
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

springdoc:
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  api-docs:
    groups:
      enabled: true # group 허용
  swagger-ui:
    path: /swagger-ui.html # swagger-ui 접근 경로 별칭, 해당 주소로 접속해도 http://localhost:8080/swagger-ui/index.html로 리다이렉션
    groups-order: DESC  # path, query, body, response 순으로 출력
    tags-sorter: alpha  # 태그를 알파벳 순으로 정렬
    operations-sorter: method # delete-get-patch-post-put 순으로 정렬 (alpha: 알파벳 순)
    disable-swagger-default-url: true
  show-login-endpoint: true
#    display-request-duration: true #Try it out 실행 후 api 실행 시간 표시
