name: frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  local_auth: ^2.2.0
  provider: ^6.1.2
  dio: ^5.4.1
  change_app_package_name: ^1.1.0
  kakao_flutter_sdk: ^1.9.0
  flutter_secure_storage: ^9.0.0

  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.1.0
  encrypt: ^5.0.3
  crypto: ^3.0.3
  flutter_native_splash: ^2.4.0
  confetti: ^0.7.0

  credit_card_scanner: ^1.0.5
  webview_flutter: ^4.7.0
  intl: ^0.19.0
  pie_chart: ^5.4.0
  table_calendar: ^3.1.1
  rive: ^0.13.1
  secure_application: ^4.0.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/

  fonts:
    - family: SUIT
      fonts:
        - asset: assets/fonts/SUIT/SUIT-Thin.ttf
          weight: 100
        - asset: assets/fonts/SUIT/SUIT-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/SUIT/SUIT-Light.ttf
          weight: 300
        - asset: assets/fonts/SUIT/SUIT-Regular.ttf
          weight: 400
        - asset: assets/fonts/SUIT/SUIT-Medium.ttf
          weight: 500
        - asset: assets/fonts/SUIT/SUIT-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SUIT/SUIT-Bold.ttf
          weight: 700
        - asset: assets/fonts/SUIT/SUIT-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/SUIT/SUIT-Heavy.ttf
          weight: 900
    - family: SCDream
      fonts:
        - asset: assets/fonts/SCDream/SCDream1.otf
          weight: 100
        - asset: assets/fonts/SCDream/SCDream2.otf
          weight: 200
        - asset: assets/fonts/SCDream/SCDream3.otf
          weight: 300
        - asset: assets/fonts/SCDream/SCDream4.otf
          weight: 400
        - asset: assets/fonts/SCDream/SCDream5.otf
          weight: 500
        - asset: assets/fonts/SCDream/SCDream6.otf
          weight: 600
        - asset: assets/fonts/SCDream/SCDream7.otf
          weight: 700
        - asset: assets/fonts/SCDream/SCDream8.otf
          weight: 800
        - asset: assets/fonts/SCDream/SCDream9.otf
          weight: 900


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
